# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@isaacs/balanced-match-4.0.1" = {
      name = "_at_isaacs_slash_balanced-match";
      packageName = "@isaacs/balanced-match";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/balanced-match/-/balanced-match-4.0.1.tgz";
        sha512 = "yzMTt9lEb8Gv7zRioUilSglI0c0smZ9k5D65677DLWLtWJaXIS3CqcGyUFByYKlnUj6TkjLVs54fBl6+TiGQDQ==";
      };
    };
    "@isaacs/brace-expansion-5.0.1" = {
      name = "_at_isaacs_slash_brace-expansion";
      packageName = "@isaacs/brace-expansion";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/brace-expansion/-/brace-expansion-5.0.1.tgz";
        sha512 = "WMz71T1JS624nWj2n2fnYAuPovhv7EUhk69R6i9dsVyzxt5eM3bjwvgk9L+APE1TRscGysAVMANkB0jh0LQZrQ==";
      };
    };
    "@isaacs/cliui-9.0.0" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-9.0.0.tgz";
        sha512 = "AokJm4tuBHillT+FpMtxQ60n8ObyXBatq7jD2/JA9dxbDDokKQm8KMht5ibGzLVU9IJDIKK4TPKgMHEYMn3lMg==";
      };
    };
    "@isaacs/fs-minipass-4.0.1" = {
      name = "_at_isaacs_slash_fs-minipass";
      packageName = "@isaacs/fs-minipass";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/fs-minipass/-/fs-minipass-4.0.1.tgz";
        sha512 = "wgm9Ehl2jpeqP3zw/7mo3kRHFp5MEDhqAdwy1fTGkHAwnkGOVsgpvQhL8B5n1qlb01jV3n/bI0ZfZp5lWA1k4w==";
      };
    };
    "@nodelib/fs.scandir-4.0.1" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-4.0.1.tgz";
        sha512 = "vAkI715yhnmiPupY+dq+xenu5Tdf2TBQ66jLvBIcCddtz+5Q8LbMKaf9CIJJreez8fQ8fgaY+RaywQx8RJIWpw==";
      };
    };
    "@nodelib/fs.stat-4.0.0" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-4.0.0.tgz";
        sha512 = "ctr6bByzksKRCV0bavi8WoQevU6plSp2IkllIsEqaiKe2mwNNnaluhnRhcsgGZHrrHk57B3lf95MkLMO3STYcg==";
      };
    };
    "@nodelib/fs.walk-3.0.1" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-3.0.1.tgz";
        sha512 = "nIh/M6Kh3ZtOmlY00DaUYB4xeeV6F3/ts1l29iwl3/cfyY/OuCfUx+v08zgx8TKPTifXRcjjqVQ4KB2zOYSbyw==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "asn1-0.2.6" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.6.tgz";
        sha512 = "ix/FxPn0MDjeyJ7i/yoHGFt/EX6LyNbxSEhPPXODPL+KB0VPk86UYfL0lMdy+KCnv+fmvIzySwaK5COwqVbWTQ==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha512 = "qeFIXtP4MSoi6NLqO12WfqARWWuCKi2Rn/9hJLEmtB5yTNr9DqFWkJRCf2qShWzPeAMRnOgCrq0sg/KLv5ES9w==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "buildcheck-0.0.7" = {
      name = "buildcheck";
      packageName = "buildcheck";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/buildcheck/-/buildcheck-0.0.7.tgz";
        sha512 = "lHblz4ahamxpTmnsk+MNTRWsjYKv965MwOrSJyeD588rR3Jcu7swE+0wN5F+PbL5cjgu/9ObkhfzEPuofEMwLA==";
      };
    };
    "bundle-name-4.1.0" = {
      name = "bundle-name";
      packageName = "bundle-name";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bundle-name/-/bundle-name-4.1.0.tgz";
        sha512 = "tjwM5exMg6BGRI+kNmTntNsvdZS1X8BFYS6tnJ2hdH0kVxM6/eVZ2xy+FqStSWvYmtfFMDLIxurorHwDKfDz5Q==";
      };
    };
    "chownr-3.0.0" = {
      name = "chownr";
      packageName = "chownr";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-3.0.0.tgz";
        sha512 = "+IxzY9BZOQd/XuYPRmrvEVjF/nqj5kgT4kEq7VofrDoM1MxoRjEWkrCC3EtLi59TVawxTAn+orJwFQcrqEN1+g==";
      };
    };
    "cpu-features-0.0.10" = {
      name = "cpu-features";
      packageName = "cpu-features";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/cpu-features/-/cpu-features-0.0.10.tgz";
        sha512 = "9IkYqtX3YHPCzoVg1Py+o9057a3i0fp7S530UWokCSaFVTc7CwXPRiOjRjBQQ18ZCNafx78YfnG+HALxtVmOGA==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "default-browser-5.5.0" = {
      name = "default-browser";
      packageName = "default-browser";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/default-browser/-/default-browser-5.5.0.tgz";
        sha512 = "H9LMLr5zwIbSxrmvikGuI/5KGhZ8E2zH3stkMgM5LpOWDutGM2JZaj460Udnf1a+946zc7YBgrqEWwbk7zHvGw==";
      };
    };
    "default-browser-id-5.0.1" = {
      name = "default-browser-id";
      packageName = "default-browser-id";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/default-browser-id/-/default-browser-id-5.0.1.tgz";
        sha512 = "x1VCxdX4t+8wVfd1so/9w+vQ4vx7lKd2Qp5tDRutErwmR85OgmfX7RlLRMWafRMY7hbEiXIbudNrjOAPa/hL8Q==";
      };
    };
    "define-lazy-prop-3.0.0" = {
      name = "define-lazy-prop";
      packageName = "define-lazy-prop";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-3.0.0.tgz";
        sha512 = "N+MeXYoqr3pOgn8xfyRPREN7gHakLYjhsHhWGT3fWAiL4IkAt0iDw14QiiEm2bE30c5XX5q0FtAA3CK5f9/BUg==";
      };
    };
    "entities-4.5.0" = {
      name = "entities";
      packageName = "entities";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
        sha512 = "V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
      };
    };
    "env-paths-3.0.0" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-3.0.0.tgz";
        sha512 = "dtJUTepzMW3Lm/NPxRf3wP4642UWhjL2sQxc+ym2YMj1m/H2zDNQOlezafzkHwn6sMstjHTwG6iQQsctDW/b1A==";
      };
    };
    "fastq-1.20.1" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.20.1.tgz";
        sha512 = "GGToxJ/w1x32s/D2EKND7kTil4n8OVk/9mycTc4VDza13lOvpUZTGX3mFSCtV9ksdGBVzvsyAVLM6mHFThxXxw==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "foreground-child-3.3.1" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.1.tgz";
        sha512 = "gIXjKqtFuWEgzFRJA9WCQeSJLZDjgJUOMCMzxtvFq/37KojM1BFGufqsCy0r4qSQmYLsZYMeyRqzIWOMup03sw==";
      };
    };
    "fs-extra-11.3.3" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.3.3.tgz";
        sha512 = "VWSRii4t0AFm6ixFFmLLx1t7wS1gh+ckoa84aOeapGum0h+EZd1EhEumSB+ZdDLnEPuucsVB9oB7cxJHap6Afg==";
      };
    };
    "fuse.js-7.1.0" = {
      name = "fuse.js";
      packageName = "fuse.js";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fuse.js/-/fuse.js-7.1.0.tgz";
        sha512 = "trLf4SzuuUxfusZADLINj+dE8clK1frKdmqiJNb1Es75fmI5oY6X2mxLVUciLLjxqw/xr72Dhy+lER6dGd02FQ==";
      };
    };
    "glob-11.1.0" = {
      name = "glob";
      packageName = "glob";
      version = "11.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-11.1.0.tgz";
        sha512 = "vuNwKSaKiqm7g0THUBu2x7ckSs3XJLXE+2ssL7/MfTGPLLcrJQ/4Uq1CjPTtO5cCIiRxqvN6Twy1qOwhL0Xjcw==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "is-docker-3.0.0" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
        sha512 = "eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
      };
    };
    "is-inside-container-1.0.0" = {
      name = "is-inside-container";
      packageName = "is-inside-container";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
        sha512 = "KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-wsl-3.1.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.0.tgz";
        sha512 = "UcVfVfaK4Sc4m7X3dUSoHoozQGBEFeDC+zVo06t98xe8CzHSZZBekNXH+tu0NalHolcJ/QAGqS46Hef7QXBIMw==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jackspeak-4.2.1" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-4.2.1.tgz";
        sha512 = "GPBXyfcZSGujjddPeA+V34bW70ZJT7jzCEbloVasSH4yjiqWqXHX8iZQtZdVbOhc5esSeAIuiSmMutRZQB/olg==";
      };
    };
    "jsonfile-6.2.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.2.0.tgz";
        sha512 = "FGuPw30AdOIUTRMC2OMRtQV+jkVj2cfPqSeWXv1NEAJ1qZ5zb1X6z1mFhbfOB/iy3ssJCD+3KuZ8r8C3uVFlAg==";
      };
    };
    "linkify-it-5.0.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-5.0.0.tgz";
        sha512 = "5aHCbzQRADcdP+ATqnDuhhJ/MRIqDkZX5pyjFHRRysS8vZ5AbqGEoFIb6pYHPZ+L/OC2Lc+xT8uHVVR5CAK/wQ==";
      };
    };
    "lru-cache-11.2.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "11.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-11.2.5.tgz";
        sha512 = "vFrFJkWtJvJnD5hg+hJvVE8Lh/TcMzKnTgCWmtBipwI5yLX/iX+5UB2tfuyODF5E7k9xEzMdYgGqaSb1c0c5Yw==";
      };
    };
    "markdown-it-14.1.0" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-14.1.0.tgz";
        sha512 = "a54IwgWPaeBCAAsv13YgmALOF1elABB08FxO9i+r4VFk5Vl4pKokRPeX8u5TCgSsPi6ec1otfLjdOpVcgbpshg==";
      };
    };
    "mdurl-2.0.0" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-2.0.0.tgz";
        sha512 = "Lf+9+2r+Tdp5wXDXC4PcIBjTDtq4UKjCPMQhKIuzpJNW0b96kVqSwW0bT7FhRSfmAiFYgP+SCRvdrDozfh0U5w==";
      };
    };
    "micromatch-4.0.8" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
        sha512 = "PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
      };
    };
    "minimatch-10.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "10.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-10.1.2.tgz";
        sha512 = "fu656aJ0n2kcXwsnwnv9g24tkU5uSmOlTjd6WyyaKm2Z+h1qmY6bAjrcaIxF/BslFqbZ8UBtbJi7KgQOZD2PTw==";
      };
    };
    "minipass-7.1.2" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
        sha512 = "qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==";
      };
    };
    "minizlib-3.1.0" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-3.1.0.tgz";
        sha512 = "KZxYo1BUkWD2TVFLr0MQoM8vUUigWD3LlD83a/75BqC+4qE0Hb1Vo5v1FgcfaNXvfXzr+5EhQ6ing/CaBijTlw==";
      };
    };
    "nan-2.25.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.25.0.tgz";
        sha512 = "0M90Ag7Xn5KMLLZ7zliPWP3rT90P6PN+IzVFS0VqmnPktBk3700xUVv8Ikm9EUaUE5SDWdp/BIxdENzVznpm1g==";
      };
    };
    "open-10.2.0" = {
      name = "open";
      packageName = "open";
      version = "10.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-10.2.0.tgz";
        sha512 = "YgBpdJHPyQ2UE5x+hlSXcnejzAvD0b22U2OuAP+8OnlJT+PjWPxtgmGqKKc+RgTM63U9gN0YzrYc71R2WT/hTA==";
      };
    };
    "package-json-from-dist-1.0.1" = {
      name = "package-json-from-dist";
      packageName = "package-json-from-dist";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
        sha512 = "UEZIS3/by4OC8vL3P2dTXRETpebLI2NiI5vIrjaD/5UtrkFX/tNbwjTSRAGC/+7CAo2pIcBaRgWmcBBHcsaCIw==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-scurry-2.0.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-2.0.1.tgz";
        sha512 = "oWyT4gICAu+kaA7QWk/jvCHWarMKNs6pXOGWKDTr7cw4IGcUbW+PeTfbaQiLGheFRpjo6O9J0PmyMfQPjH71oA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "punycode-2.3.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.3.1.tgz";
        sha512 = "vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
      };
    };
    "punycode.js-2.3.1" = {
      name = "punycode.js";
      packageName = "punycode.js";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode.js/-/punycode.js-2.3.1.tgz";
        sha512 = "uxFIHU0YlHYhDQtV4R9J6a52SLx28BCjT+4ieh7IGbgwVJWO+km431c4yRlREUAsAmt/uMjQUyQHNEPf0M39CA==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "readline-sync-1.4.10" = {
      name = "readline-sync";
      packageName = "readline-sync";
      version = "1.4.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/readline-sync/-/readline-sync-1.4.10.tgz";
        sha512 = "gNva8/6UAe8QYepIQH/jQ2qn91Qj0B9sYjMBBs3QOB8F2CXcKgLxQaJRP76sWVRQt+QU+8fAkCbCvjjMFu7Ycw==";
      };
    };
    "reusify-1.1.0" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.1.0.tgz";
        sha512 = "g6QUff04oZpHs0eG5p83rFLhHeV00ug/Yf9nZM6fLeUrPguBTkTQOdpAWWspMh55TZfVQDPaN3NQJfbVRAxdIw==";
      };
    };
    "run-applescript-7.1.0" = {
      name = "run-applescript";
      packageName = "run-applescript";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-applescript/-/run-applescript-7.1.0.tgz";
        sha512 = "DPe5pVFaAsinSaV6QjQ6gdiedWDcRCbUuiQfQa2wmWV7+xC9bGulGI8+TdRmoFkAPaBXk8CrAbnlY2ISniJ47Q==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-7.7.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.4.tgz";
        sha512 = "vFKC2IEtQnVhpT78h1Yp8wzwrf8CM+MzKMHGJZfBtzhZNycRFnXsHk6E5TxIkkMsgNS7mdX3AGB7x2QM2di4lA==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "spdx-exceptions-2.5.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.5.0.tgz";
        sha512 = "PiU42r+xO4UbUS1buo3LPJkjlO7430Xn5SVAhdpzzsPHsjbYVflnnFdATgabnLude+Cqu25p6N+g2lw/PFsa4w==";
      };
    };
    "spdx-expression-parse-4.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-4.0.0.tgz";
        sha512 = "Clya5JIij/7C6bRR22+tnGXbc4VKlibKSVj2iHvVeX5iMW7s1SIQlqu699JkODJJIhh/pUu8L0/VLh8xflD+LQ==";
      };
    };
    "spdx-license-ids-3.0.22" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.22.tgz";
        sha512 = "4PRT4nh1EImPbt2jASOKHX7PB7I+e4IWNLvkKFDxNhJlfjbYlleYQh285Z/3mPTHSAK/AvdMmw5BNNuYH8ShgQ==";
      };
    };
    "ssh2-1.17.0" = {
      name = "ssh2";
      packageName = "ssh2";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssh2/-/ssh2-1.17.0.tgz";
        sha512 = "wPldCk3asibAjQ/kziWQQt1Wh3PgDFpC0XpwclzKcdT1vql6KeYxf5LIt4nlFkUeR8WuphYMKqUA56X4rjbfgQ==";
      };
    };
    "supports-color-10.2.2" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "10.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-10.2.2.tgz";
        sha512 = "SS+jx45GF1QjgEXQx4NJZV9ImqmO2NPz5FNsIHrsDjh2YsHnawpan7SNQ1o8NuhrbHZy9AZhIoCUiCeaW/C80g==";
      };
    };
    "tar-7.5.7" = {
      name = "tar";
      packageName = "tar";
      version = "7.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-7.5.7.tgz";
        sha512 = "fov56fJiRuThVFXD6o6/Q354S7pnWMJIVlDBYijsTNx6jKSE4pvrDTs6lUnmGvNyfJwFQQwWy3owKz1ucIhveQ==";
      };
    };
    "tmp-0.2.5" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.2.5.tgz";
        sha512 = "voyz6MApa1rQGUxT3E+BK7/ROe8itEx7vD8/HEvt4xwXucvQ5G5oeEiHkmHZJuBO21RpOf+YYm9MOivj709jow==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha512 = "KXXFFdAbFXY4geFIwoyNK+f5Z1b7swfXABfL7HXCmoIWMKU3dmS26672A4EeQtDzLKy7SXmfBu51JolvEKwtGA==";
      };
    };
    "uc.micro-2.1.0" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-2.1.0.tgz";
        sha512 = "ARDJmphmdvUk6Glw7y9DQ2bFkKBHwQHLi2lsaH6PPmz/Ka9sFOBsBluozhDltWmnv9u/cF6Rt87znRTPV+yp/A==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wsl-utils-0.1.0" = {
      name = "wsl-utils";
      packageName = "wsl-utils";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wsl-utils/-/wsl-utils-0.1.0.tgz";
        sha512 = "h3Fbisa2nKGPxCpm89Hk33lBLsnaGBvctQopaBSOW/uIs6FTe1ATyAnKFJrzVs9vpGdsTe73WF3V4lIsk4Gacw==";
      };
    };
    "xhr2-0.2.1" = {
      name = "xhr2";
      packageName = "xhr2";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr2/-/xhr2-0.2.1.tgz";
        sha512 = "sID0rrVCqkVNUn8t6xuv9+6FViXjUVXq8H5rWOH2rz9fDNQEd4g0EA2XlcEdJXRz5BMEn4O1pJFdT+z4YHhoWw==";
      };
    };
    "yallist-5.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-5.0.0.tgz";
        sha512 = "YgvUTfwqyc7UXVMrB+SImsVYSmTS8X/tSrtdNZMImM+n7+QTriRXyXim0mBrTXNeqzVF0KWGgHPeiyViFFrNDw==";
      };
    };
    "yaml-2.8.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.2.tgz";
        sha512 = "mplynKqc1C2hTVYxd0PU2xQAc22TI1vShAYGksCCfxbn/dFwnHTNi1bvYsBTkhdUNtGIf5xNOg938rrSSYvS9A==";
      };
    };
  };
  args = {
    name = "spago";
    packageName = "spago";
    version = "1.0.3";
    src = ./..;
    dependencies = [
      sources."@isaacs/balanced-match-4.0.1"
      sources."@isaacs/brace-expansion-5.0.1"
      sources."@isaacs/cliui-9.0.0"
      sources."@isaacs/fs-minipass-4.0.1"
      sources."@nodelib/fs.scandir-4.0.1"
      sources."@nodelib/fs.stat-4.0.0"
      sources."@nodelib/fs.walk-3.0.1"
      sources."argparse-2.0.1"
      sources."asn1-0.2.6"
      sources."bcrypt-pbkdf-1.0.2"
      sources."braces-3.0.3"
      sources."buildcheck-0.0.7"
      sources."bundle-name-4.1.0"
      sources."chownr-3.0.0"
      sources."cpu-features-0.0.10"
      sources."cross-spawn-7.0.6"
      sources."default-browser-5.5.0"
      sources."default-browser-id-5.0.1"
      sources."define-lazy-prop-3.0.0"
      sources."entities-4.5.0"
      sources."env-paths-3.0.0"
      sources."fastq-1.20.1"
      sources."fill-range-7.1.1"
      sources."foreground-child-3.3.1"
      sources."fs-extra-11.3.3"
      sources."fuse.js-7.1.0"
      sources."glob-11.1.0"
      sources."graceful-fs-4.2.11"
      sources."is-docker-3.0.0"
      sources."is-inside-container-1.0.0"
      sources."is-number-7.0.0"
      sources."is-wsl-3.1.0"
      sources."isexe-2.0.0"
      sources."jackspeak-4.2.1"
      sources."jsonfile-6.2.0"
      sources."linkify-it-5.0.0"
      sources."lru-cache-11.2.5"
      sources."markdown-it-14.1.0"
      sources."mdurl-2.0.0"
      (sources."micromatch-4.0.8" // {
        dependencies = [
          sources."picomatch-2.3.1"
        ];
      })
      sources."minimatch-10.1.2"
      sources."minipass-7.1.2"
      sources."minizlib-3.1.0"
      sources."nan-2.25.0"
      sources."open-10.2.0"
      sources."package-json-from-dist-1.0.1"
      sources."path-key-3.1.1"
      sources."path-scurry-2.0.1"
      sources."picomatch-4.0.3"
      sources."punycode-2.3.1"
      sources."punycode.js-2.3.1"
      sources."queue-microtask-1.2.3"
      sources."readline-sync-1.4.10"
      sources."reusify-1.1.0"
      sources."run-applescript-7.1.0"
      sources."run-parallel-1.2.0"
      sources."safer-buffer-2.1.2"
      sources."semver-7.7.4"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."spdx-exceptions-2.5.0"
      sources."spdx-expression-parse-4.0.0"
      sources."spdx-license-ids-3.0.22"
      sources."ssh2-1.17.0"
      sources."supports-color-10.2.2"
      sources."tar-7.5.7"
      sources."tmp-0.2.5"
      sources."to-regex-range-5.0.1"
      sources."tweetnacl-0.14.5"
      sources."uc.micro-2.1.0"
      sources."universalify-2.0.1"
      sources."which-2.0.2"
      sources."wsl-utils-0.1.0"
      sources."xhr2-0.2.1"
      sources."yallist-5.0.0"
      sources."yaml-2.8.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "🍝 PureScript package manager and build tool";
      homepage = "https://github.com/purescript/spago";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
